template: Hello, %s!
defaultName: Stranger

logging:
  level: INFO
  loggers:
    io.harness.payments: DEBUG


mongo:
  connectionString: ""

swagger:
  basePath: /validation
  resourcePackage: io.harness.payments
  scan: true
  info:
    version: "1.0.0"
    title: "Payments Validation API Doc"
    description: "A simple API used for Banking Demo"
    termsOfService: "http://swagger.io/terms/"
    contact:
      name: "Payments Validation API"
    license:
      name: "Diego Pereira"