template: Hello, %s!
defaultName: Stranger

logging:
  level: INFO
  loggers:
    io.harness.payments: DEBUG


mongo:
  connectionString: "mongodb://admin:harnessbankingdemo@mongo-replicaset-0.mongo-replicaset-svc.prod.svc.cluster.local:27017,mongo-replicaset-1.mongo-replicaset-svc.prod.svc.cluster.local:27017,mongo-replicaset-2.mongo-replicaset-svc.prod.svc.cluster.local:27017/admin?ssl=true"

swagger:
  basePath: /auth
  resourcePackage: io.harness.payments
  scan: true
  info:
    version: "1.0.0"
    title: "Payments Validation API Doc"
    description: "A simple API used for expose some operation on MongoDB collection"
    termsOfService: "http://swagger.io/terms/"
    contact:
      name: "Payments Validation API"
    license:
      name: "Diego Pereira"